query paginatedPokemonsBis($offset: Int!, $limit: Int!) {
  paginatedPokemons(offset: $offset, limit: $limit)
    @connection(key: "otherFeed", filter: []) {
    id
    name
    cartouche
    type
  }
}
