"use client";

import Head from "next/head";
import styles from "@/styles/Home.module.css";

import { useQuery } from "@apollo/client";
import { PokemonList } from "@/components/PokemonList";
import { DresseurList } from "@/components/DresseurList";
import { PaginatedPokemonList } from "@/components/PaginatedPokemonList";
import { PaginatedPokemonListBis } from "@/components/PaginatedPokemonListBis";
import { UpdatePokemon } from "@/components/UpdatePokemon";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.card}>
          <UpdatePokemon id={4} name={"Mewto"} />
        </div>
        <div className={styles.card}>
          <UpdatePokemon id={23} name={"Elektor"} />
        </div>
        <div className={styles.card}>
          <UpdatePokemon id={2} name={"Luigi"} />
        </div>
        <div className={styles.card}>
          <UpdatePokemon id={13} name={"Sendido"} />
        </div>
      </main>
      <main className={styles.main}>
        <PokemonList />
        <DresseurList />
      </main>
      <main className={styles.main}>
        <PaginatedPokemonList />
        <PaginatedPokemonListBis />
      </main>
    </>
  );
}
